stages:
  - build
  - test
  - release


build-bletl:
  stage: build
  image: python:3.8
  script:
    - pip install -U pip pep517 twine
    - cd bletl
    - python -m pep517.build .
    - cp dist/*.whl ..
  artifacts:
    paths:
      - ./*.whl
    expire_in: 30 days

build-bletl-analysis:
  stage: build
  image: python:3.8
  script:
    - pip install -U pip pep517 twine
    - cd bletl_analysis
    - python -m pep517.build .
    - cp dist/*.whl ..
  artifacts:
    paths:
      - ./*.whl
    expire_in: 30 days
 

test-bletl-py38:
  stage: test
  image: python:3.8
  script:
    - pip install pytest pytest-cov
    - pip install -e bletl
    - cd bletl
    - pytest --cov=./bletl --cov-report term-missing tests/tests.py

test-bletl-analysis-py38:
  stage: test
  image: python:3.8
  script:
    - pip install pytest pytest-cov
    - pip install -e bletl
    - pip install -e bletl_analysis
    - cd bletl_analysis
    - pytest --cov=./bletl_analysis --cov-report term-missing tests/tests.py


release-bletl:
  stage: release
  image: python:3.8
  script:
    - pip install -U pip pep517 twine pytest
    - cd bletl
    - python -m pep517.build .
    - pip install dist/*.whl
    - pytest tests/tests.py
    - cp dist/*.whl ..
  artifacts:
    paths:
      - ./*.whl
    expire_in: 30 yrs
  only:
    # only run on refs that are named like v1.2 or v1.2.3
    - /^bletl_v(\d+\.)?(\d+\.)?(\*|\d+)$/
  except:
    - branches

release-bletl-analysis:
  stage: release
  image: python:3.8
  script:
    - pip install -U pip pep517 twine pytest
    - cd bletl_analysis
    - python -m pep517.build .
    - pip install dist/*.whl
    - pytest tests/tests.py
    - cp dist/*.whl ..
  artifacts:
    paths:
      - ./*.whl
    expire_in: 30 yrs
  only:
    # only run on refs that are named like v1.2 or v1.2.3
    - /^bletl_analysis_v(\d+\.)?(\d+\.)?(\*|\d+)$/
  except:
    - branches
