name: pipeline

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.10", "3.11"]
        pymc-version: ["without", "'pymc>=5.0.0'"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install -e .
        pip install -r requirements-dev.txt
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --statistics
    - name: Test without PyMC
      if: matrix.pymc-version == 'without'
      run: |
        pytest --cov=./bletl --cov-report xml --cov-report term-missing tests/
    - name: Install and test with PyMC
      if: matrix.pymc-version != 'without'
      run: |
        pip install ${{ matrix.pymc-version }}
        pytest --cov=./bletl --cov-report xml --cov-report term-missing tests/
    - name: Upload coverage
      uses: codecov/codecov-action@v5
      with:
        file: ./coverage.xml
    - name: Test Wheel build, install and import
      run: |
        python setup.py bdist_wheel
        twine check dist/*
        cd dist
        pip install bletl*.whl
        python -c "import bletl; print(bletl.__version__)"
